Run crawl (of WARC) tests on travis
webrecorder/browsertrix-old pull request #3
Opened 2019-04-09 17:23 UTC by ikreymer

2019-04-11 19:16 UTC, N0taN3rd requested changes

2019-04-11 19:16 UTC, N0taN3rd commented on requirements.txt
> -cchardet
cchardet (for aiohttp), pandantic, and starlette (we directly import these) should stay.

2019-04-11 19:16 UTC, N0taN3rd commented on mypy.ini
> -[mypy]
we use mypy via flake8-mypy :)

2019-04-11 19:16 UTC, N0taN3rd commented on crawlmanager/crawl.py
> +import logging
is there any reason why we are jacking uvicorns logger rather than using our own?

Also we should keep all imports sorted like below and move the logger variable below `__all__``

```suggestion
from __future__ import annotations

import logging
import uuid
from asyncio import AbstractEventLoop, gather as aio_gather, get_event_loop
from functools import partial
from typing import Dict, List, Optional, Union
from urllib.parse import urlsplit

from aiohttp import AsyncResolver, ClientSession, TCPConnector
from aioredis import Redis
from starlette.exceptions import HTTPException
from ujson import dumps as ujson_dumps

from .schema import CrawlInfo, CreateCrawlRequest, StartCrawlRequest
from .utils import env, init_redis

__all__ = ['Crawl', 'CrawlManager']

logger = logging.getLogger('uvicorn')
```

2019-04-11 19:16 UTC, N0taN3rd commented on README.md
> +python setup.py install
setup.py is not required unless distributing or installing this project globally
rather should be pip install -r requirements since these directions are for running within the repo

```suggestion
pip install -r requirements.txt -r dev-requirements.txt
```

2019-04-11 19:16 UTC, N0taN3rd commented on .dockerignore
> +#tests
I think it would be best to not include the tests in the docker container.
If we do need them it should be a separate dev container

2019-04-13 22:04 UTC, ikreymer commented on requirements.txt
> -cchardet
Adding pydantic and starlette actually breaks the install, because the latest versions aren't compatible with latest fastapi. We don't want the latest version of these or even to worry about which version to use, but rather use whichever version is installed when fastapi is installed.

2019-04-15 18:21 UTC, merged